language: scala
 
scala:
  - 2.10.6
  - 2.11.7
   
matrix:
  fast_finish: true
  allow_failures:
    - scala: 2.11.7

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
  
sudo: false
   
# Re-add scalastyle later
script: "sbt ++$TRAVIS_SCALA_VERSION stats test"
