language: scala
 
scala:
  - 2.10.5
  - 2.11.7
  - 2.12.0-M1
   
matrix:
  fast_finish: true
  allow_failures:
    scala:
      - 2.11.7
      - 2.12.0-M1

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
  
sudo: false
   
script: "sbt ++$TRAVIS_SCALA_VERSION scalastyle test"
